service: my-service

frameworkVersion: '3'

provider:
  name: aws
  iam:
    role: arn:aws:iam::159757278796:role/AdministratorRoleTest

functions:
  message:
    handler: handler.error
    destinations:
      onFailure: arn:aws:sns:us-east-1:159757278796:Test.fifo
      onSuccess: arn:aws:sns:us-east-1:159757278796:Test.fifo
    events:
      - httpApi: 'GET /error'
  retry:
    handler: handler.retry
    events:
      - httpApi: 'GET /retry'